18F/charlie

- package.json
- scripts/glossary.coffee
Added a glossary listener to get an explanation of an abbreviation/jargon.
Usage: `hubot glossary <abbreviation>` would return a defined term
Example: 
`hubot glossary ATO` returns:
> The term Authority to Operate (ATO) means: A sign-off from an authorized agency official for a website to be allowed to engage with citizens, including security and some other stuff. Historically this is a 3-6 month process, but 18F has been working to fix this.
> added glossary.coffee

- scripts/glossary.coffee
See 34d72b4 – it was working locally because `console.log()` shows up, but the response wasn't actually making it back to Slack. Also made it match terms case-insensitively.
> fix glossary script

- package.json
Looks like #42 isn't live yet after all:
```
OUT -----> Installing binaries
OUT        engines.node (package.json):  4.2.3
OUT        engines.npm (package.json):   unspecified (use default)
OUT        Downloading and installing node 4.2.3...
ERR DEPENDENCY MISSING IN MANIFEST: node 4.2.3
ERR It looks like you're trying to use node 4.2.3.
ERR Unfortunately, that version of node is not supported by this buildpack.
ERR The versions of node supported in this buildpack are:
ERR - 4.2.2
...
```
cc: @afeld @ccostino
> Set Node engine to 4.2.2

- scripts/opm_status.coffee
I realized that it was much more useful to add the "AppliesTo" date field to the message, because without that field it is confusing to see what date the message references.
> update opm message to include date

- package.json
Contains improvements from 18F/unit-testing-node as applied in 18F/hubot-slack-github-issues#43 (and the entry point fix from 18F/hubot-slack-github-issues#45).
Confirmed with both `npm run validate-config` and `bin/hubot` (the latter command finding the entry point problem fixed in 18F/hubot-slack-github-issues#45).
cc: @afeld
> Bump hubot-slack-github-issues to ^1.0.1

- scripts/glossary.coffee
Procurement terms can be multiple words and can include non-word characters (e.g., ampersands, parentheses, etc.).  This PR modifies the regex to capture them all.
Closes 18F/procurement-glossary#8
> Catch all procurement terms for the glossary/define

- scripts/glossary.coffee
The upgrade to js-yaml 3.5.5 brought along a slightly stricter parser that throws an error on duplicate keys. Rather than have Charlie just not respond if the glossary yaml is imperfect, tell js-yaml to ignore duplicate key errors.
This is done by just adding { json: true } as an option to the yaml.safeLoad method call.
> Less-strict YAML parsing

- config/slack-github-issues.json
I'd like to set up this hook so that we can easily tag pithy answers in #cloud-gov-support for addition to cloud.gov documentation.
> Bookmark in #cloud-gov-support -> cg-docs

- config/slack-github-issues.json
The repository this points do moved, and as a result we got
```
Error: failed to create a GitHub issue in 18F/cg-docs: received 307 response from GitHub API: {"message":"Moved Permanently","url":"https://api.github.com/repositories/29991068/issues","documentation_url":"https://developer.github.com/v3/#http-redirects"}
```
> Follow renamed repository

- scripts/tock_line.coffee
If Charlie is in a channel, he can be told to assign that channel a tock line.  Users can then ask him later what the tock line is.
Set a tock line:
```
@charlie set tock line 100 / DevOps / Bots / Charlie
```
> Okay, I set the tock line for this room
Retrieve a tock line:
```
@charlie tock line
```
> The tock line for #channel is `100 / DevOps / Bots / Charlie`
> Save and report tock lines

- start.sh
Per [Cloud Foundry documentation] use of `$VCAP_APP_HOST` and `$VCAP_APP_PASSWORD` are incompatible with newer (Diego-based) Cloud Foundry deployments. This change makes this repository forward compatible with the new cloud.gov environment deployment in AWS GovCloud.
> Cloud Foundry Diego compatibility

- package.json
- start.sh
Instead of requiring that the redis URL be set with `cf set-env`, read it from the `VCAP_SERVICES` env at startup and set it that way.  Just makes it a little easier.
> Get redis URL from VCAP_SERVICES

- config/slack-github-issues.json
- package.json
Use the :standup-bot: emoji reaction to create an issue in the https://github.com/18F/standup-slack-bot repo.
> Enable github issues for standup-bot channel

- package.json
The `slack-github-issues` script doesn't work correctly with private channels or DMs.  There are open PRs to fix it ([private channels](https://github.com/mbland/slack-github-issues/pull/4) and [direct messages](https://github.com/mbland/slack-github-issues/pull/3), but until that gets merged, let's use our fork.
The problem appears when users add an emoji reaction to a message in a private channel.  Charlie responds in-channel with an error about an undefined property:
> For now, use our fork

- package.json
Now that [mbland/slack-github-issues](https://github.com/mbland/slack-github-issues) is fixed for private channels and DM, let's switch back to it!
> Switch back to @mbland's slack-github lib since it's fixed

- external-scripts.json
- package.json
These scripts no longer appear to work, so might as well get rid of them.
> Remove google images and translate, both of which are apparently broken

- external-scripts.json
And Hubot doesn't understand thread comments, so its responses to thread comments go to the main channel, which increases confusion related to image responses in general.
> Ship-it script has too many broken images

- external-scripts.json
- package.json
The trollbot script is confusing some people, who don't know why a bot is criticizing them, and annoying other people, who would prefer to do their work without a snarky bot making judgment. It might work in an environment where everybody is a developer, but that is not the case.
> remove trollbot script

- config/slack-github-issues.json
The [Design Wiki repo](https://github.com/18F/Design-Wiki) is private and Charlie can't get to it (an issue related to 2FA).  Until we resolve that, let's remove this config so Charlie doesn't shout about `404` errors any time someone adds a `:dart:` emoji reaction.
> Remove Design-Wiki Github issue config

- README.md
- package-lock.json
- package.json
- scripts/gsa-approved-software.js
Charlie can look up software on the GSA IT Standards list (from [this CSV](https://github.com/GSA/data/blob/gh-pages/enterprise-architecture/it-standards.csv)) and report what it finds.  It responds to @-messages in the form of `@charlie Is <app> approved`, or indirect messages of the form `<app> is approved?` (e.g., "does anyone know if Chrome is approved?").
There's a limitation with the latter, indirect form, in that Charlie will only catch the last word before "is," the reasoning being that there's no way to know what might have come before that shouldn't be considered part of the search.
If Charlie finds 5 or fewer matching apps, it posts this, where the colors correspond to approval status:
If it finds more, it posts this:
Credit to @andrewmaier for the idea!  😄
> Query GSA IT Standards for approved software

- hubot-scripts.json
- scripts/zen.coffee
Instead of using the [hubot-scripts zen script](https://github.com/github/hubot-scripts/blob/master/src/scripts/zen.coffee) that responds to _every_ mention of the word `zen`, use a custom script that only responds when the bot is directly addressed.  E.g., `@charlie zen`.
> Use less intrusive customized zen script

- scripts/xpost.coffee
When Charlie successfully XPOSTs, add an emoji reaction to the original message instead of responding with a new message of its own.
Closes #35
> Emoji XPOST confirmation

- docker-compose.yml
- start.sh
Redis 2.x is being deprecated by cloud.gov.  This PR updates Charlie's environment handling to use connection info for a 3.2 service that is now attached to the charlie app.  Data from the 2.8 database has been migrated over.
Closes #118
> Have Charlie use attached redis 3.2 service

- docker-compose.yml
- scripts/startup_announce.js
- test/scripts/startup_announce.js
When the bot starts, post a message to the channel described in the `HUBOT_STATUS_CHANNEL` environment variable (or `#bots` by default).  That way if the bot needs a reboot, folks in the channel will know it has happened.
Hopefully the bot doesn't just restart all the time and we end up flooded with messages, but that'd be useful information to know, anyway.  😬
> Have the bot announce when it boots up

- .cfignore
Unlinks `.cifignore` from `.gitignore`.  This way we push `node_modules` into cloud.gov when we deploy.  Then the npm dependency versions deployed to cloud.gov are the same as the ones that were tested on CircleCI.  (Closes the loop on the `npm ci` change in #140)
> Fixup .cfignore

- .snyk
The vulnerability warning from Snyk is not relevant.  It comes in via Sinon, so it would only manifest during testing, where no "real" data is accessible.  There's no available patched version yet, so just suppress the warning for now.
> Suppress specific vulnerability dependency warning

- .snyk
- Dockerfile
- docker-compose.yml
- package-lock.json
- package.json
- Updates to a newer `hubot-slack` that fixes an issue with reactji support.
- Updates Dockerfile to use `npm ci` instead of `npm install`, to more closely mirror the deployment environment
- Updates `docker-compose.yml` to name and tag the 18F-bot image for faster switching between sets of dependencies (useful when upgrading dependencies and switching between branches)
- Adds npm `postinstall` script to update `docker-compose.yml` and set the image version to the md5 hash of `package-lock.json`
> Update hubot-slack to fix reactji support

- scripts/coffeemate.coffee
- makes the key used to retrieve/store the coffee queue from/to the brain a const
- empties the local queue when users are paired up, not just the stored queue
> const for brain key; reset local queue too

- .circleci/config.yml
- .eslintrc.json
- package-lock.json
- package.json
- scripts/coffeemate.coffee
- scripts/glossary.coffee
- scripts/hugme.coffee
- scripts/love.coffee
- scripts/opm_status.coffee
- scripts/random-responses.js
- scripts/roles.coffee
- scripts/tock_line.coffee
Adds eslint with the airbnb config plus support for linting coffeescript, and jiggles code a little bit in order to pass.  I tried to add linting to the tests as well, but it choked on the places where the tests wanted to import coffeescript files and it didn't really seem worth spending a ton of time trying to figure out.
> Add linting

- package.json
The Node.js buildpack on cloud.gov doesn't yet include the 12.13.x line, so downgrade slightly to the highest supported version.
> Switch to a Node.js version supported by cloud.gov

- scripts/hugme.coffee
- scripts/opm_status.coffee
- Tweaks the OPM open/close status message to put the status URL into a link with text, and disables unfurling the link to reduce clutter:
- Fixes a bug in the `hugme` script where it would continue to try to load even after discovering that S3 credentials were not set
> Tweak OPM open/close status message

- scripts/opm_status.coffee
Following up on a request from @ToniBonittoGSA:
> Can the Charlie/O P M status bot be updated? Someone triggered it yesterday (I think trying to check for today's status a day ahead) and it had this:
> > :greenlight: Open for December 10, 2019. Open. (Read more)
Looks like the message is using the icon text to determine `:greenlight:` as well as echoing it out immediately after as a status summary — and then using the API-provided status summary later in the message, leading to the duplicate. 
According to [their status types API](https://www.opm.gov/developer/documentation/status-types-api/) we should be able to use `StatusSummary` for the first occurrence and it’ll make a pretty okay sentence: 
> :greenlight: Open for December 10, 2019. (Read more)
> :yellowlight: Delayed Arrival for …
> Update OPM status message text.

- .eslintrc.json
- package-lock.json
- package.json
- scripts/travel-team.js
- test/scripts/travel-team.js
If a user sends a message in the #travel channel during a weekend or on a holiday, Charlie will automatically respond to them. Charlie will only respond to a user once every 3 hours to (hopefully) prevent spamming. We can tweak this later if we need to.
Here's an example of what the message looks like:
> Adds a weekend/holiday auto-response to the travel channel

- scripts/angry-tock.js
- test/scripts/angry-tock.js
When Angry Tock runs on Monday afternoons, send a list of truants to the #tock channel as well as DM'ing the truant users. The goal is to make it easy for timekeeping and reporting folks to know whose timesheets might need manual tweaking.
> Add a truancy report to a management channel

- scripts/angry-tock.js
- test/scripts/angry-tock.js
Prior to this bug, Solutions, Login, cloud.gov, separated, etc. staff would be reported in the 18F GMT channel. This fixes that, so only current 18F employees should be reported.
> Fixes a bug where everyone who has not Tocked is reported in the GMT channel, not just current 18F staff

- manifest.yml
The manifest was pointing at the old Redis service, which was deprecated like... a year and a half or more ago. We've been using the newer service, but the manifest still referenced the old one. When I took down the old Redis service last week, it broke the manifest. This PR fixes the manifest.
> fix manifest to point to correct redis

- .circleci/deploy.sh
- .dependabot/config.yml
Dependabot is rather noisy, especially with `aws-sdk` getting multiple version bumps per day. To tone down the noise, configure it to only open PRs for security-related updates, not every version bump.
> Configure Dependabot to only create PRs for security fixes

- package-lock.json
- package.json
So we can't actually *completely* remove it yet.
> Coffeescript runtime is required for Hubot

- scripts/timezone.js
- test/scripts/timezone.js
The use case for this is handling messages like:
`1pm :eastern-time-zone: | 12pm :central-time-zone: | 11am :mountain-time-zone: | 10am :pacific-time-zone:`
but the regex will end up matching any times in the message whether or not they refer to the same real time.
I _think_ that case is no worse than the current implementation where it will only act on the first time it finds, with the chance for more users to be accidentally filtered out than would have currently been filtered, but I could be wrong.
> Handle messages with multiple timezones already included

- scripts/inclusion-bot.yaml
`blind leading the blind` is an idiom used to describe a situation where people who don't know what they're doing are being directed by people who don't know what they're doing, and is a terrible and incorrect association to make with people who don't have eyesight.
> Update inclusion-bot.yaml to suggest alternatives to 'blind leading the blind'

- src/scripts/coffeemate.js
- src/scripts/coffeemate.test.js
Allow `coffee me` requests to be scoped. Scopes are a single word after `coffee me`, and people will only be matched with others who request coffee from the same scope. Hopefully the screenshot below demonstrates:
Closes #274
> Coffeemate-bot scopes

- src/scripts/erg-inviter.test.js
- src/scripts/opt-out.test.js
- src/utils/test.js
Two recent additions both implemented a bit of logic for accessing an action handler for testing. This PR pulls that into the test utilities instead, and tidies up how the test utility gets the handler out of the array a bit.
> Minor test cleanup

- src/scripts/handbot.js
- src/scripts/handbot.test.js
Triggered by any of these:
```
handbook <search terms>
@handbook <search terms>
handbot <search terms>
@handbot <search terms>
```
Looks like the screenshot in the #284, but with the TTS logo for an icon and "TTS Handbot" as a name. Puts its response into a thread so it doesn't clutter up the channel. Displays the response publicly instead of an "only you can see this message" because the request might actually be useful to multiple people at once.
- closes #284
> Implement Handbot, the TTS Handbook search helper

- src/scripts/timezone.js
- src/scripts/timezone.test.js
When detected time is considered invalid, will not return an "invalid" message to the user
Alters tests with user region / city abbreviations to be more intuitive when reading tests.
Adds passing tests for invalid time, and time ranges around midnight
Adds a skipped test for 24 hour time which accompanies #292 
Closes https://github.com/18F/charlie/issues/257
> Invalid time conversion fix

- package-lock.json
- package.json
- src/scripts/optimistic-tock.js
- src/scripts/optimistic-tock.test.js
Like with the tiny tau bot, messages from Happy Tock will include the little three-dot button:
Clicking it will show a drop-down menu that contains the option to stop receiving these messages.
cc: @lauraGgit
---
Also updated dependencies, as a matter of course. The `@slack/bolt` dependency made a major version jump, but no breaking changes that affected us. However, the older version had a bug that was making opting out of Happy Tock impossible, so it was kind of a convenient time to update. The `node-schedule` dependency also made a major version jump, but it didn't impact us. All the others were in-range updates.
> Allow users to opt-out of "Optimistic Tock" reminders

- src/scripts/inclusion-bot.yaml
We want to trigger on slang uses of "bipolar," but when someone is talking about bipolar disorder, the bot shouldn't chime in. (See [the Slack comment](https://gsa-tts.slack.com/archives/C02DJFR0V/p1622222665164700) that inspired this PR.)
> Update the inclusion bot so it ignores "bipolar disorder"

- src/scripts/inclusion-bot.js
- src/scripts/inclusion-bot.test.js
This will allow people to have conversations about words without being spammed by the bot. For example, this text will not trigger the bot:
```
Let's talk about "ninja" movies
```
> For Inclusion Bot, ignore utterances that are in quotes

- src/scripts/encourage-bot.js
- src/scripts/encourage-bot.test.js
This bot schedules future cheers between 2 and 48 hours in the future! That's great! But it's statistically most likely to schedule for the next day, always, and that's not really a problem except that the bot is automatically restaged every night with the practical upshot that the bot basically just never runs because it's perpetually rescheduled for tomorrow.
The fix: let the bot stash the scheduled time in its brain and use that at startup.
> Poor encouragement bot, hardly ever gets to run

- src/scripts/angry-tock.test.js
- src/scripts/federal-holidays-reminder.js
- src/scripts/federal-holidays-reminder.test.js
- reorganize the Angry Tock tests so there are fewer "and"s in the test descriptions
- gets rid of tests that test internal functionality of the holiday reminder script because that's a bad practice
closes #261
> Refactor tests

- package-lock.json
- package.json
- src/scripts/angry-tock.test.js
- src/scripts/dad-joke.test.js
- src/scripts/encourage-bot.test.js
- src/scripts/federal-holidays-reminder.test.js
- src/scripts/federal-holidays.test.js
- src/scripts/optimistic-tock.test.js
- src/scripts/travel-team.test.js
- src/scripts/what-day-is-it.test.js
- src/utils/cache.test.js
- src/utils/dates.test.js
- src/utils/tock.js
- src/utils/tock.test.js
- update Jest to 27
- switches from Sinon fake timers to Jest timers, to remove a dependency
- sort of: Jest uses Sinon under the hood
- after changing the timers, there was only one Sinon use left, so switches that to Jest mocks
- uninstalls Sinon
- fixes a bug that accidentally worked until it was fixed in 37, where spying on functions of modules kinda sorta worked, but now it doesn't at all, so switches to module mocks
closes #316
> Update to Jest 27

- src/scripts/encourage-bot.js
- src/scripts/encourage-bot.test.js
Saying `@charlie encourage` will cause the bot to encourage a random person in the triggering channel. It will still filter to only users who are within nominal working hours (9am to 5pm local time).
> Allow random encouragements to be manually triggered

- config/slack-random-response.json
Slack automatically transforms `lovin.gov` into a link, which is then sent in the message as `<http://lovin.gov|lovin.gov>`. This PR updates the trigger regex to account for that link-ification. Makes the the linky part optional in the regex in case there is a Slack client that _doesn't_ do the transformation for some reason.
> Tweak lovin.gov trigger regex

- src/scripts/dad-joke.js
- src/scripts/dad-joke.test.js
Just changing the avatar between messages does not guarantee that it will display separately; the username for the response must change too. But we want Jed Bartlett to be the username for both! So... insert a zero-width space into the username for the response so that it's technically different but you can't tell.
> Dad Joke bot setup fix

- .github/workflows/auto_approve.yml
It turns out that when using the GitHub CLI non-interactively and you tell it to merge a PR, you have to tell it what merging strategy to use. Which totally makes sense, but... it's not documented. 🙁
> You know what's fun? A dozen pull requests testing a CI/CD thing

- src/scripts/random-responses.js
- src/scripts/random-responses.test.js
Adds functionality to the random response handler to take into account the word preceding the triggering phrase to filter potential responses. For example, `whale giraffe fact` will filter out the list of giraffe facts to just the ones containing the word "whale." If the filtered list is empty, defaults to the full set of facts.
> Support kind of asking for a particular subset of facts

- package-lock.json
- package.json
- src/scripts/random-responses.js
- src/scripts/random-responses.test.js
Major kudos to @bengerman13 for figuring this one out.
Now if you say `hat dog fact`, it will first try to find facts that include just `hat`, not `that`. It will fall back to the more inclusive version if the more restrictive search fails. It will also look for plurals, which is pretty cool!
> Add word boundary and plural support to the random fact filter

- src/scripts/coffeemate.js
- src/scripts/coffeemate.test.js
Previously, coffeemate would trigger on `coffee meeting`, but that's... wrong. This tweaks the regex that it's listening for so that it only matches `coffee me`.
> Fix a bug where coffeemate matches too aggressively

- src/scripts/encourage-bot.js
- src/scripts/encourage-bot.test.js
There is room to expand on this, but as a first go, it would be nice not to @-mention folks who have put in their status message that they're not around.
> For encourage users, skip over users with "OOO" or "vacation" in their Slack status message

- config/q-expand.csv
Aware that 18F portfolios have sunset, there are still staff who retain related org codes (e.g. QUEBC), but those org codes are returning `?`s.
[Example](https://gsa-tts.slack.com/archives/C028GH7FA/p1638984788009300):
```
qex QUEBC
QUEBC
||||└──QUEBC: ???
```
This commit adds in the org codes using the [latest TTS org chart](https://docs.google.com/presentation/d/1otRbhoGRN4LfDnWpN6zZ0ymjPpTBW3t79pIiuBREkCY/edit#slide=id.gf510aca337_3_198) as the source of truth.
> Add org codes from TTS org chart to q-expander

- src/scripts/inclusion-bot.yaml
"No problemo" is mock Spanish and arose as a way of devaluing Spanish in favor of an "English-only" United States. Recommend "no problem" or proper Spanish "no hay problema" instead.
> Add "no problemo" to Inclusion Bot

- src/scripts/define.js
- src/scripts/define.test.js
Previously, searching `backend developer` to find `back end developer` didn't work. Now it does, by ignoring all non-alphanumeric characters in the search string.
Fixes #388
> `define` matches terms more flexibly

- README.md
- config/slack-random-response.json
- src/scripts/a11y.js
- src/scripts/a11y.test.js
This pr does two small things to set the foundation for more work on A11yBot. 
-    "ask ally or ask a11y" will now return the menu, which is about to grow as we add functionality.
-    The original "ask ally" functionality of returning a random fact now requires the command "ask ally fact".
> Add a static menu for A11y and change commands

- config/q-expand.csv
- src/scripts/q-expand.test.js
This PR adds 400+ more titles to the Q-Expander bot.
This PR makes it look like a few old titles were removed. They weren't sorted, so this also sorts those so they're easier to find.
Also some titles may be cut off. This is because the spreadsheet has some titles cut off due to length. I just haven't found all of them yet and some of them I don't know what the rest of the word is. Figured adding partially complete titles was better than leaving them off.
> Add MANY more Q-Expander titles

- .github/workflows/nightly_restage.yml
Charlie's `dev` instance should be stopped when nobody is actively using it, to save on cost. This PR updates the nightly restage automation so that it also stops the `dev` instance as well, so if we forget - which we will - it'll automatically stop itself overnight.
> Stop dev instances during nightly restage

- src/scripts/inclusion-bot.yaml
"Macademia nuts" triggered the inclusion bot in #food. This PR adds exceptions using the biggest list of two-word nut terms I could find in a quick search.
> Add list of nuts for #food

- src/scripts/coffeemate.js
- src/scripts/coffeemate.test.js
Currently the regex requires that the text `coffee me` be followed by whitespace or the end of the line, which means it does not match `coffee me, please` or `coffee me.` with punctuation. This PR changes the requirement so that `coffee mate` is followed by a word boundary, and also preceded by one, to make it easier to trigger the bot without making it more likely to do so accidentally.
> Make the coffeemate regex more permissive

- external-scripts.json
- src/scripts/coffeemate.js
- src/scripts/coffeemate.test.js
- src/scripts/erg-inviter.js
- src/scripts/erg-inviter.test.js
- src/scripts/federal-holidays.js
- src/scripts/federal-holidays.test.js
- src/scripts/home.js
- src/scripts/home.test.js
- src/utils/homepage.js
- src/utils/homepage.test.js
- src/utils/index.js
- src/utils/index.test.js
- src/utils/test.js
This pull request adds coffeemate and the ERG (employee resource/affinity group) inviter to Charlie's homepage.
---
Into the technical weeds a little bit:
This PR also adds a `homepage` utility that existing scripts can use to register themselves on the homepage. They do this by passing a callback that is called when the homepage is being created. The script can then create [Slack Block Kit](https://api.slack.com/block-kit) objects to define what should be displayed on the homepage. They can return either a single object or an array.
The `home` script will use the `homepage` utility to call all of the scripts that registered themselves and insert their return values into the page that it builds. The `home` script also registers a handler to manually refresh the homepage. Slack will …
> Add some of Charlie's interactive functionality to its homepage

- src/scripts/inclusion-bot.js
- src/scripts/inclusion-bot.test.js
Per [conversation on Slack](https://gsa-tts.slack.com/archives/C02FPFGBG/p1656524008103759), the `:inclusion-bot:` emoji kind of looks like a flashing bus and people have commented about getting hit by the inclusion bus. That's kind of funny in some ways, but it doesn't satisfy the purpose of the bot's reaction emoji. So this PR changes it to 👋.
> Change Inclusion Bot's reaction emoji

- .github/workflows/codeql-analysis.yml
- src/scripts/pugs.test.js
The CodeQL v1 action [is being deprecated](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/) later this year. Let's just go ahead and update, then.
> Update CodeQL to newer version

- config/q-expand.csv
Time for some new names.
Goodbye to Chumanjalaal.
(Still an Easter egg…)
-----
Updates `config/q-expand.csv` to reflect these new Engineering cohort names: 
*   QUEAAD/Dingobots.
*   QUEAAE/Electronachos.
*   QUEAAG/Glamgoyles.
> Q-expander: update Engineering Chapter cohort names.

- src/scripts/federal-holidays-reminder.js
- src/scripts/federal-holidays-reminder.test.js
When I updated the holiday reminder script to take its configuration via an injected variable defaulting to the process environment variables (instead of always directly referring to environment variables; this was meant to be an enhancement to testability), I forgot that the first argument to scripts is ***always*** the bot object. So this:
```javascript
const scheduleReminder = (config = process.env) => {
...
};
```
Well, that just never works. The `config` variable is always set to the bot, not to environment variables. Then when the script checks for the channel, posting time, etc., it doesn't find them so it reverts to its own hardcoded defaults. The default channel is `general`, which does not exist in the TTS Slack, so the end result is this script just stopped announcing holidays …
> Fix the holiday reminder

- src/scripts/q-expand.test.js
In #449, a test is failing because the test is attempting to "parse" the CSV by simply splitting on commas. However, it is valid for a CSV value to include commas if the value is wrapped in quotes. This PR updates the test to use the `csv-parse` library to parse the CSV and then counts the fields based on that.
> Use csv-parse to test CSV correctness

- .github/workflows/reusable_deploy.yml
The workflow for deployments was pointing to the wrong path for builds so... it doesn't deploy. 😬
---
Checklist:
- N/A ~The `oauth.md` file has been updated if Charlie needs any new OAuth
events or scopes~
- N/A ~The `env.md` file has been updated if any changes have been made to the
environment variables Charlie uses~
- N/A ~The dev wiki has been updated, e.g.:~
- N/A ~If appropriate, the NIST 800-218 documentation has been updated~
> Fix a workflow

- src/scripts/federal-holidays.js
- src/scripts/federal-holidays.test.js
Also make the regex a little bit looser so it's easier to trigger without triggering accidentally.
Closes #469 
---
Checklist:
- N/A The `oauth.md` file has been updated if Charlie needs any new OAuth
events or scopes
- N/A The `env.md` file has been updated if any changes have been made to the
environment variables Charlie uses
- N/A The dev wiki has been updated, e.g.:
- N/A If appropriate, the NIST 800-218 documentation has been updated
> Base holiday emoji on the displayed holiday name rather than the official holiday name

- src/scripts/angry-tock.js
- src/scripts/angry-tock.test.js
- src/scripts/optimistic-tock.js
- src/scripts/optimistic-tock.test.js
- src/utils/slack.js
- src/utils/slack.test.js
* Adds a Slack utility method for fetching users' status text (the status message you can set yourself from Slack)
* Adds another Slack utility for getting a boolean whether a user is OOO or not
* Updates AngryTock and OptimisticTock to check users' OOO status and not pester people who are gone
* Updates all the tests too.
After review and approval, the wiki needs to be updated:
* A new OAuth scope is required: `users.profile:read` - the Charlie app will need to be reinstalled in the TTS workplace afterwards (which I _think_ I can do)
* Two new utility APIs need to be added to the documentation
---
Checklist:
events or scopes
- N/A ~The `env.md` file has been updated if any changes have been made to the
environment variables Charlie uses~
- major …
> Don't send messages to users whose status message indicates they are OOO

- src/scripts/federal-holidays-reminder.js
- src/scripts/federal-holidays-reminder.test.js
This PR shifts an 18F norm into Charlie. For the last few years, 18F has made it a point to remind staff that they are expected to do less work during holiday weeks, as there is less working time to do it in. Holiday works have less time in them, so it is only reasonable that less should be done. Now Charlie will remind folks when it posts holiday reminders in Slack.
---
Checklist:
- other points are N/A
> Remind people not to overwork themselves in holiday weeks

- src/scripts/angry-tock.js
- src/scripts/angry-tock.test.js
- src/scripts/optimistic-tock.js
- src/scripts/optimistic-tock.test.js
- src/utils/slack.js
- src/utils/slack.test.js
Reverts 18F/charlie#471
Optimistic and Angry Tock both seem to have stopped working entirely. I can't reproduce the problem in staging, but there is a hint: the production logs and my staging tests have both triggered rate limiting warnings. Possibly querying each user's status is pushing us over the rate limit and that's causing problems. Bolt is supposed to handle rate limit warnings and automatically retry requests after the specified cooldown, and since Charlie is asynchronously waiting for Bolt, that ***should*** still be fine, but #471 is the only recent change to Tock reporting and at least one user mentioned in #bots that they didn't get a reminder after it was merged.
Some thoughts for revisiting this in the future:
1. It may not be necessary to fetch the entire list of Slack …
> Revert "Don't send messages to users whose status message indicates they are OOO"

- .github/workflows/on_pull_request_tock_ops.yml
- src/scripts/angry-tock.js
- src/scripts/angry-tock.test.js
- src/scripts/hugme.js
- src/scripts/tock-truant-ops-report.js
- src/scripts/tock-truant-ops-report.test.js
- src/utils/cache.js
- src/utils/cache.test.js
- src/utils/dates.js
- src/utils/dates.test.js
- adds a new date utility for getting the days of the current working week (and leaves out days that are holidays)
- removes ops report from Angry Tock
- updates Angry Tock to use date utility to schedule its shouting matches
- adds a new script for ops reporting
- adds a GitHub action that detects changes to the new ops reporting script and reminds PR authors to collaborate with the 18F director of operations
- closes #480 
---
Checklist:
> Refactor ops reports for Tock truancy out of Angry Tock

- src/utils/dates.js
- src/utils/dates.test.js
The date utility helper `getCurrentWorkWeek` currently returns a list of `Date` objects. These objects include a UTC timestamp, which can cause issues when transforming into the reporting timezone. Rather than dealing with that, this PR opts to return a date string of the form `YYYY-MM-DD` and let utility consumers decide what to do with that. Happily, using the Moment.js timezone-aware factory with a date string works as expected, creating an object whose time component is midnight in the specified timezone. And also happily, the parts of Charlie that current using `getCurrentWorkWeek` also use that factory method.
This is intended to fix a bug where some timed events would actually happen a day earlier than expected. For example, Angry Tock's first "shout."
---
Checklist:
- internal …
> Update the work week utility to be more reliable

- src/scripts/angry-tock.js
- src/scripts/angry-tock.test.js
- src/scripts/optimistic-tock.js
- src/scripts/optimistic-tock.test.js
- src/utils/tock.js
- src/utils/tock.test.js
Charlie uses email addresses stored in Tock and Slack to correlate a user in one with a user in another. It currently does a case-sensitive comparison, which works in most cases, but at least one person's email address in Slack has capital letters while their email address in Tock does not. They did not receive any Optimistic or Angry Tock reminders as a result.
This PR modifies the tests for Angry Tock, Optimistic Tock, and the Tock utility library to add case mismatches in the mocked data. Those tests promptly failed. This PR then updates those bits of code to do case-insensitive comparisons and make the updated tests pass.
---
Checklist:
- the rest is N/A
> Bug fix: Use a case-insensitive comparison between Tock and Slack email addresses

- src/scripts/angry-tock.js
- src/scripts/optimistic-tock.js
- src/utils/tock.js
#486 introduced a case-insensitive comparison for emails, but it turns out that emails can sometimes be undefined or null. As a result, Charlie promptly crashes on startup when it's scheduling Tock reminders (these are based on Tockable users' timezones, and email comparison is necessary to figure out which Slack users are Tockable).
This fixes that bug by using optional chaining. If the email is null or undefined, the whole chain will be treated as `undefined` and that's just fine.
---
Checklist:
- n/a
> Crashing bug: Email addresses from Slack and/or Tock are sometimes empty

- .github/workflows/on_pull_request_tock_ops.yml
- src/scripts/angry-tock.js
- src/scripts/angry-tock.test.js
- src/scripts/optimistic-tock.js
- src/scripts/optimistic-tock.test.js
- src/scripts/tock-ops-report.js
- src/scripts/tock-ops-report.test.js
- src/utils/tock.js
- src/utils/tock.test.js
#492 describes how the word "truant" has *not great* implications, and we might want to avoid those. This PR removes the word "truant" in most of the code and, most importantly, from user-facing messages. A future issue would be to rename the environment variables that configure the Tock ops report as well.
Closes #492
---
Checklist:
> Remove the word "truant"

- .github/workflows/on_push_main.yml
The thing is referencing a version of the GitHub checkout action that does not exist. This PR updates that thing to reference a version that does exist.
> Fix a bug with the thing that creates releases on publish to main

- .github/workflows/reusable_deploy.yml
- .github/workflows/wait-for-database.sh
- src/brain.js
The dev deploy creates a database if one does not already exist. This is because the dev database is automatically removed nightly to keep cloud.gov costs down. However, the action for deploying didn't work correctly. The code for waiting until the database was ready was broken. Furthermore, new Postgres databases require an SSL connection, which our client wasn't offering. This PR fixes both things.
---
Checklist:
- N/A ~The [OAuth](https://github.com/18F/charlie/wiki/OAuthEventsAndScopes) wiki page has been updated if Charlie needs any new OAuth events or scopes~
- N/A ~The [Environment Variables](https://github.com/18F/charlie/wiki/EnvironmentVariables) page has been updated if new environment variables were introduced or existing ones changed~
- N/A ~The dev wiki has been updated~
- …
> Fix dev deploy

- config/slack-random-response.json
This adds a bot for alumni dag intros, for our dag pals whose people have moved on
---
Checklist:
> add alumni dag intros

- src/scripts/federal-holidays.js
- src/scripts/federal-holidays.test.js
closes #514
---
Checklist:
(rest are N/A)
> If holiday is requested in a thread, respond in the thread

- src/scripts/us-code.js
- src/scripts/us-code.test.js
Slack imposes a limit of 3,000 characters on `text` fields. Some US Code citations (many, many, probably) exceed this limit. This PR composes the code text into a single string and then breaks it into chunks that are less than but nearly 3,000 characters long and puts each of those into a unique block, satisfying the Slack constraint.
- closes #539
---
Checklist:
> Break US code text into multiple blocks, if the total text is too long

- src/scripts/random-responses.js
- src/scripts/random-responses.test.js
It would be super neat if our random responses could define a random emoji to be used when posting them. This PR makes that so. Screambot will be in for such a delightful update.
---
Checklist:
- ~The [OAuth](https://github.com/18F/charlie/wiki/OAuthEventsAndScopes) wiki
- ~The [Environment Variables](https://github.com/18F/charlie/wiki/EnvironmentVariables)
or existing ones changed~
- The dev wiki has been updated, e.g.:
- ~major development workflows have changed~
- ~internal utilities or APIs have changed~
- ~testing or deployment processes have changed~
- ~If appropriate, the NIST 800-218 documentation …
> Random default emoji!

- src/scripts/federal-holidays-reminder.js
- src/scripts/federal-holidays-reminder.test.js
TTS Slack guidance, linked below, advises against using @here for large-channel messages.
TTS staff gets lots of reminders about upcoming federal holidays. While the work-life balance reminder is appreciated, there's not a clear, compelling reason to break Slack guidance in this context.
This commit removes `@here` from federal holiday reminders.
https://handbook.tts.gsa.gov/tools/slack/notifications-general-communication/#here-and-channel-notifications
Describe what this pull request is doing. If there are associated issues,
cite those here as well.
---
Checklist:
- major …
> Remove @here notifications

- README.md
- src/scripts/bio-art.js
- src/scripts/bio-art.test.js
- src/utils/slack.js
This PR adds a new Charlie listener for `bio-art`, `bio art`, or `bioart` that queries the [NIH BioArt](https://bioart.niaid.nih.gov/) API and fetches a random image. The image is then posted to Slack along with the art title and the name of the creator. For example:
There is a new OAuth scope required: `files.write`. I will update Charlie's configuration and the wiki after this PR is approved and before merging it.
---
Checklist:
- ~The [Environment Variables](https://github.com/18F/charlie/wiki/EnvironmentVariables)
or existing ones changed~
- ~The dev wiki has been updated, e.g.:~
- ~If appropriate, the NIST 800-218 documentation has been …
> Add BioArt

- src/scripts/evermarch.js
- src/scripts/evermarch.test.js
The Evermarch script mistakenly calculated time from March 1, 2020, midnight UTC, instead of midnight America/New_York as intended. Additionally, it was calculating the time difference in milliseconds and then dividing that into a number of days, which meant it was not accounting for leap years or DST.
---
Checklist:
N/A:
- The [OAuth](https://github.com/18F/charlie/wiki/OAuthEventsAndScopes) wiki
- The [Environment Variables](https://github.com/18F/charlie/wiki/EnvironmentVariables)
- The dev wiki has been updated, e.g.:
- internal …
> Fixes a couple of bugs related to UTC offsets and day-counting.

- config/q-expand.csv
- src/scripts/q-expand.test.js
#577 included data with a trailing comma. The comma was present in the source data, so this adds a check to not allow trailing commas in any values.
Confirmed that the additional validation fails as expected in https://github.com/18F/charlie/actions/runs/16997197191/job/48190665972
---
Checklist:
> Improve q-expand data validation
