.cfignore, Procfile, package.json, scripts/love.coffee, start.sh
Verified by deploying the branch.
/cc @yozlet @dlapiduz @ozzyjohnson
=> Cloud Foundry configuration

external-scripts.json, package.json
Adding this Hubot plugin: https://github.com/andypiper/hubot-cf/pull/3
/cc @ozzyjohnson @dlapiduz
=> show Cloud Foundry deployment notifications

external-scripts.json, package.json
Wrote it a while ago, but never got around to publishing/incorporating it.
https://github.com/afeld/hubot-trollbot
=> add trollbot

scripts/hugme.coffee
Because it's important.
/cc @dlapiduz
=> send unique hug URLs in each `hug bomb`

external-scripts.json, package.json
https://github.com/18F/hubot-cf-notifications
/cc @dlapiduz @ozzyjohnson
=> switch to using standalone hubot-cf-notifications plugin

cf_config.json, package.json
=> add Cloud Foundry config

README.md
=> update production info

CONTRIBUTING.md, LICENSE.md, README.md
=> Add License, Contribution guidelines

package.json, scripts/hugme.coffee
Also made it easier to add new images: no environment variables need be changed, nor do the images need any special naming convention.
/cc @dlapiduz
=> include instructions for how to be added to the `hug bomb`

scripts/xpost.coffee
From a workshop I did with @wslack, @ertzeid, and @goodnightjj.
=> [WIP] add basic crossposting script

README.md
cc @ozzyjohnson and @dlapiduz but self-merging since this is trivial and we just talked about it.
=> Updates with instructions to join the devops org

cf_config.json
=> Configure FEC notifications

config/slack-github-issues.json, external-scripts.json, package.json
Working on deploying with @afeld; will hopefully have it deployed tomorrow.
cc: @andrewmaier @melodykramer @dlapiduz @ccostino @mtorres253
=> Slack GitHub issues

package.json
Failed to resolve in Cloud Foundry: https://travis-ci.org/18F/18f-bot/builds/97476012.
/cc @mbland
=> change Node version specifier

config/slack-github-issues.json, hubot-scripts.json, package.json
Would like to have @melodykramer, @andrewmaier, and @jeremiak look over the rules to make sure they're the way they want them before we merge.
After that, would love to have @afeld do the honors of firing away.
cc: @ccostino @mtorres253
=> Use official hubot-slack-github-issues npm release

bin/hubot, config/README.md, package.json
Integrates the hubot-slack-github-issues config validation command.
cc: @afeld @ccostino @ertzeid @andrewmaier
=> Add `npm run validate-config` command

config/slack-github-issues.json
Fire when ready, @annahsebok or @andrewmaier.
=> koala emoji => 18F/product-guide

config/README.md
cc: @afeld @andrewmaier @melodykramer @annahsebok @ccostino @ertzeid @mtorres253
=> Document web-based slack-github-issues validator

scripts/opm_status.coffee
This command pings the opm api and returns the current status with a summary and a green light/stoplight/yellow light emoji for what the alert is.
=> add opm status command

scripts/opm_status.coffee
making Moncef's suggested changes to just display the link and fix the Closed status to display a stoplight emoji instead of a yellowlight.
=> update url and change closed to stoplight emoji

package.json
Contains bugfix from 18F/hubot-slack-github-issues#46.
cc: @afeld @annahsebok
=> Bump hubot-slack-github-issues to v1.0.2

config/slack-github-issues.json
I'd like to create an issue in the Design-Wiki repo when a slack message is marked with a :dart: emoji
=> Create Design-Wiki issue

config/slack-github-issues.json
Edited the design wiki emoji to work in all channels
=> Removed channel name for design wiki dart emoji

config/slack-github-issues.json
https://pages.18f.gov/hubot-slack-github-issues/
=> reorder config based on validator

hubot-scripts.json
=> Removes alot script

scripts/security.coffee
cc @micahsaul and @konklone - unsure if we need to run hubot locally to test this...
I did verify that hubot doesn't care about https in front of URLs in #transient.
=> add script for fugacious warnings

scripts/xpost.coffee
Disabling XPOST from private channels means it'll be safe to bring Charlie into those channels for other purposes!
=> Disallow XPOST from private channels

scripts/xpost.coffee
Thanks to @wslack for pointing this one out.
=> Fix xpost again

.travis.yml, manifest.yml, package.json, scripts/hugme.coffee
Changed deployer credentials
Imported cfenv to read s3 service credentials for HugMe
Removed domain entry in manifest in favor of brokered cdn-route
=> Migrated Hubot to GovCloud

.travis.yml
Updated with GovCloud credentials
=> Use GovCloud credentials

external-scripts.json, package.json
Adds the reading list plugin to the bot
=> Add reading list plugin

scripts/xpost.coffee
Query the Slack API to see if Charlie is in the target channel rather than just firing it and hoping for the best.  This also lets us let users know if Charlie is able to send the xpost or not.
=> XPOST: Check if Charlie is in the target channel

external-scripts.json, package.json
Remove the YouTube script.  Closes #45.
=> Remove YouTube

scripts/xpost.coffee
Based on #36.
If the bot hears `xpost` in a public room, but the message doesn't satisfy the full pattern that it recognizes, it posts a message explaining how to use xpost:
Also expands the pattern to be more forgiving of xpost patterns.  It now accepts:
* `xpost #channel`
* `xpost to #channel`
* `xpost in #channel`
Closes #36
=> Friendlier XPOST

scripts/xpost.coffee
Allows the bot to cross-post to multiple channels at once.  E.g.:
```
hello world! xpost #general-talk #random #transient
```
CC: @wslack
Closes #34
=> Multi-channel x-post

scripts/dag_fact.coffee
and a good opportunity to practice using github too
=> adding a ripley dag fact!

scripts/gsa-approved-software.js
The `gh_pages` branch was deleted.  Key off master instead.
=> Fix approved software list

scripts/dag_fact.coffee
=> Update dag facts

scripts/dag_fact.coffee, test/scripts/dag_fact.js
When responding to dag fact requests, masquerade as "Dag Bot"
=> Respond to dag fact requests as Dag Bot

scripts/dag_fact.coffee, test/scripts/dag_fact.js
=> Use dag emoji as Dag Bot avatar

scripts/dag_fact.coffee
Trying something out here that might be fun. 😄 
I'd love for the name to be the dags name and not **Dag Bot (Charlie)**
=> Update pixie dag facts to be in the first dag

config/slack-random-response.json
Depends on https://github.com/18F/18f-bot-facts/pull/6
Don't merge until that's merged.
=> Add cat facts bot

.snyk, scripts/coffeemate.coffee, test/scripts/coffeemate.js
So that people don't look like they're just shouting into the void, have Charlie add an emoji to "coffee me" messages so folks know it responded.
=> Respond to coffeemate requests with an emoji

docker-compose.yml, package-lock.json, package.json
Updates dependencies, including downstream lodash to resolve vulnerabilities
=> Dependency update

docker-compose.yml, package-lock.json, package.json, scripts/random-responses.js
=> Add a response to get a random fact of facts

package-lock.json, package.json
=> Update in-range dependencies

config/slack-random-response.json
=> Add screambot responses

.circleci/config.yml, scripts/angry-tock.js, test/scripts/angry-tock.js
This will filter out more users who shouldn't be getting notified.
=> Use Tock's UserData API's new is_active flag

scripts/what-day-is-it.js
=> Tell us what day of the week it is, and also which day of March 2020

scripts/guys-bot.js, test/scripts/guys-bot.js, test/utils.js, utils.js
Does some of the stuff in #209:
- updates language
- makes messages ephemeral so only the user who triggered the bot sees them
- adds an emoji reaction to messages that the bot responds to, to signal to the rest of the team that it has been addressed
---
=> Some Inclusion bot updates

scripts/angry-tock.js, test/scripts/angry-tock.js
:hat_tip: @abrouilette 
There's some noise in this PR because prettier decided to add trailing commas to a bunch of stuff. 🤷‍♂️
=> Use animated Tock emoji when messaging users

scripts/what-day-is-it.js
20% of the time, call the current day `Blursday`, and 20% of the time call the month `Evermarch`.
=> Blursday, Evermarch

.circleci/deploy.sh, .github/workflows/main.yaml, .github/workflows/pull_requests.yml
Just what it says on the tin. Let's hold this PR until #239 goes in, since we can't be sure that the deploy script is going to work yet. Not 100% sure about the thing with installing Node inside the `governmentpaas/cf-cli` container, but we'll see!
=> Move deploys to GitHub Actions

.github/workflows/pull_requests.yml, manifest.yml, test/utils.js, utils.js
=> Add cacheing for Slack and Tock API calls

.circleci/config.yml
=> Nightly restages

scripts/what-day-is-it.js
Just what it says on the tin...
=> Be prepared for the end of March 2020

src/scripts/dad-joke.js, src/scripts/dad-joke.test.js
Jokes taken from our friends at HHS and fatherhood.gov. Charlie will answer requests for dad jokes:
=> Charlie learns to tell dad jokes

src/scripts/love.js, src/scripts/love.test.js
Currently Charlie tries to send love messages to #love, but that channel is archived. Instead, let's send them to #kudos where people will see them!
=> Send love notices to a real channel that exists

src/scripts/handbot.js, src/scripts/handbot.test.js
=> Light refactor of Handbot for readability

CONTRIBUTING.md, README.md
also includes table of contents to jump past list of commands
=> adds documentation for local / docker development

.github/workflows/nightly_restage.yml, .github/workflows/pull_requests.yml
- add nightly restage to Github Actions from CircleCI
- add cf variables to deploy
=> GitHub Actions transition fixes

src/scripts/dad-joke.js, src/scripts/dad-joke.test.js
named after President Josiah Bartlett, Martin Sheen's character in the West Wing
=> rename username of charlie's dad joke bot

package-lock.json, package.json, src/scripts/encourage-bot.js, src/scripts/encourage-bot.test.js, src/utils/slack.js, src/utils/test.js
Periodically let a random person know they're awesome. We all deserve reminders.
=> Encourage bot

src/scripts/encourage-bot.js
The previous algorithm for selecting a next random encouragement time was biased towards mornings. The reason is that it was ***likely*** to pick a time outside of working hours simply because working hours only account for about 35% of the hours in a week (accounting for timezones and weekends). For times outside of working hours, it would then advance the time by hours until it reached working hours again. Thus, it was always more likely to trigger in the morning hours.
The new algorithm randomizes the hours to be within working hours so there's no need to advance the hours at all. This should result in random encouragements happening more uniformly throughout the day.
=> Update encourage bot so it does not bias towards mornings

README.md
Poor Charlie's documentation is missing a few things
=> Update Charlie's readme to list everything

src/scripts/dad-joke.js, src/scripts/dad-joke.test.js
Current behavior responds into the channel instead of the thread, which is confusing for everyone involved.
=> If someone requests a dad joke in a thread, respond in the thread

src/scripts/dad-joke.js, src/scripts/dad-joke.test.js
Concept courtesy of @bengerman13.
=> Have a setup avatar for dad joke bot

src/utils/holidays.js
Having a skin tone on the Labor Day emoji struck me as odd. @mgwalker suggested this emoji as a replacement
=> swap Labor Day emoji

.github/workflows/auto_approve.yml
Just what it says on the tin. I'm not certain this will work, but unfortunately the only way to test it is to merge it.
=> Automatically approve and merge Dependabot PRs

src/utils/tock.js
For a brief period, we had a special case in our Tock data. Tock is now updated, so we can rely on it to provide us accurate information.
I kind of don't want to open this PR.
=> Tock has been updated and we can rely on it as the definitive source of information now

.github/workflows/auto_approve.yml
I'm not sure if this will work since the PR comes from dependabot, but it *looks* like the branch is in the source repo, not a branch. 🤞🏻
=> Need a git ref in order to determine where the pull request is

.github/workflows/auto_approve.yml
I'm turning off the conditional until I get the behavior I want, because I just realized I didn't actually have to turn the whole thing off. I hope y'all enjoy seeing all these tomorrow.
=> I'm determined to make this work

src/scripts/inclusion-bot.yaml
https://gsa-tts.slack.com/archives/C0X2T36AY/p1635978112016300
> Wow, Inclusion Bot tagged me for including a URL that included the word n-i-n-j-a. :blob-eyeroll:
=> Don't trigger for TMNT chatter and URLS

.github/workflows/pull_requests.yml, Dockerfile, package-lock.json, package.json
Just what it says on the title. Tested in dev! ~Still needs to be tested in dev to make sure everything actually works.~
=> Update to Node 16 (LTS) and update dependencies

config/slack-random-response.json
A different bot trigger so we can ask for doggie intros:
=> Adds a new source of random responses: dag intros

src/scripts/inclusion-bot.yaml
=> New inclusion bot additions

config/slack-random-response.json
Adds the cat intros bot that points to the cat-intros.json file, triggered by any mention of "cat intro" or "cat intros".
=> Add cat intros

config/q-expand.csv
Add “/10x” to QQF.
-----
A generic name
Does seem inevitable
But let's add 10X
=> Add 10x to QQF

config/slack-random-response.json
Does just what it claims to do!
=> Add presidential facts

config/q-expand.csv, src/scripts/q-expand.test.js
This is a trivial temporary change and I'm fine if nobody wants to merge this until we have new cohort names :)
=> Update engineering cohorts

config/q-expand.csv
This PR updates the QEX branches for Login.gov
=> Update Login QEX branches

.github/workflows/nightly_restage.yml
Forgot to actually import the secret that the action needs in order to stop the test instance 🤦🏻‍♂️
=> Fix dev shutdown

config/q-expand.csv, src/scripts/q-expand.test.js
=> update 18F eng cohort QUEAAC name

src/scripts/erg-inviter.yaml
Adds the women and neurodiversity employee affinity/resource groups.
=> Add additional employee affinity/resource groups to the ones Charlie knows about and can help people find

config/q-expand.csv
[As of May 25](https://gsa-tts.slack.com/archives/C032CE7LAC9/p1653509411280479), we’ve got a new name!
=> Update QUEAAA name.

CONTRIBUTING.md, README.md
=> Update docs to point to the wiki

config/slack-random-response.json
note: requires PR merge from the charlie-slack-bot-facts repo first for URL to work
=> pointer to hyrax facts

src/scripts/erg-inviter.yaml
Just what it says on the tin!
---
Checklist:
- other items are all N/A
=> Add the Not-Your-Dude affinity group to the inviter

src/scripts/erg-inviter.yaml
per @geekygirlsarah; see #475, which was causing problems because it was an already-merged branch, which shouldn't have mattered but GitHub was being weird.
---
Checklist:
=> Update channel name to Womxn to match syntax of rest of description

.github/pull_request_template.md, src/scripts/i-voted.js, src/scripts/i-voted.test.js, src/utils/dates.js, src/utils/dates.test.js
On Election Day, post a message to `#general-talk` inviting folks to the `#i-voted` channel for a fun democracy party.
---
Checklist:
- N/A ~The `oauth.md` file has been updated if Charlie needs any new OAuth
events or scopes~
- N/A ~The [OAuth](https://github.com/18F/charlie/wiki/OAuthEventsAndScopes) wiki
- N/A ~local development processes have changed~
- N/A ~major development workflows have changed~
- N/A ~testing or deployment processes have changed~
- N/A ~If appropriate, the NIST 800-218 documentation has been updated~
=> Election day reminder

README.md
This PR corrects some minor typos and refreshes the table of contents for the repo's README. 
Thank you for the hard work to build up and maintain this repo. I love the elements of fun weaved throughout (pug bot, raven attacks, etc). Keep up the great work!
---
Checklist:
page has been updated if Charlie needs any new OAuth events or scopes  
or existing ones changed 
=> Update Charlie's readme - minor typos

.eslintrc.js, .github/workflows/on_pull_request_inclusion_bot_sync.yml, .github/workflows/on_schedule_monthly.yml, lts.js, lts.test.js, package.json
Adds a weekly check to verify that Charlie is using the current LTS version of Node.
closes #457 
---
Checklist:
=> Check if Charlie is using the current LTS

.github/workflows/on_pull_request_inclusion_bot_sync.yml, .github/workflows/on_push_main.yml, .github/workflows/reusable_build.yml, .github/workflows/reusable_test.yml, Dockerfile, package.json
Updates us to Node 18
---
Checklist:
* N/A ~The `oauth.md` file has been updated if Charlie needs any new OAuth
events or scopes`~
* N/A ~The `env.md` file has been updated if any changes have been made to the
environment variables Charlie uses~
* N/A ~The dev wiki has been updated, e.g.:~
* N/A ~If appropriate, the NIST 800-218 documentation has been updated~
=> Update to Node 18 (new LTS)

config/slack-random-response.json
Updates the random fact bot to know about bird facts and the new consolidate pet facts.
---
Checklist:
- the rest is n/a
=> Add bird and pet MEGA-FACTS

src/scripts/inclusion-bot.yaml
Adding "Crazy Egg" as an exception: this is a product some teams are using.
---
Checklist:
=> Add exception "Crazy Egg" in inclusion-bot.yaml

src/scripts/inclusion-bot.yaml
Ignoring "Insane Clown Posse," a band name
---
Checklist:
=> Update inclusion-bot.yaml to ignore a band name

config/slack-random-response.json
- add alumni cat intros
- silence non-alumni intros during alumni intros
---
Checklist:
=> add alumni cat intros, don't double-intro

src/scripts/random-responses.js, src/scripts/random-responses.test.js
closes #529
---
Checklist:
the rest are N/A
=> Support negated searches

README.md
closes #532
---
Checklist:
- N/A ~The [OAuth](https://github.com/18F/charlie/wiki/OAuthEventsAndScopes) wiki
- N/A ~The [Environment Variables](https://github.com/18F/charlie/wiki/EnvironmentVariables)
or existing ones changed~
- N/A ~The dev wiki has been updated, e.g.:~
- ~local development processes have changed~
- ~major development workflows have changed~
- ~internal utilities or APIs have changed~
- ~testing or deployment processes have changed~
- N/A ~If appropriate, the NIST 800-218 documentation has been updated~
=> Add bird facts to README

README.md, config/slack-random-response.json
Updates the configuration to include NPS facts.
=> Add national park facts

README.md, config/slack-random-response.json
Adds dinosaur facts
---
Checklist:
=> Add dinosaur facts

src/scripts/random-responses.js, src/scripts/random-responses.test.js
=> Don't unfurl links in random responses

config/slack-random-response.json
Just what it says on the tin.
---
Checklist:
- ~The [OAuth](https://github.com/18F/charlie/wiki/OAuthEventsAndScopes) wiki
- ~The [Environment Variables](https://github.com/18F/charlie/wiki/EnvironmentVariables)
or existing ones changed~
- ~The dev wiki has been updated, e.g.:~
- ~local development processes have changed~
- ~major development workflows have changed~
- ~internal utilities or APIs have changed~
- ~testing or deployment processes have changed~
- ~If appropriate, the NIST 800-218 documentation has been updated~
=> Give screambot several emoji options

config/slack-random-response.json
Just exactly what it says on the tin.
---
Checklist:
N/A:
- The [OAuth](https://github.com/18F/charlie/wiki/OAuthEventsAndScopes) wiki
- The [Environment Variables](https://github.com/18F/charlie/wiki/EnvironmentVariables)
- The dev wiki has been updated, e.g.:
- If appropriate, the NIST 800-218 documentation has been updated
=> Add trivia!

config/slack-random-response.json
Just what it says on the tin.
---
Checklist:
All N/A
=> Change the trivia emoji avatar

src/scripts/dad-joke.json
Added a joke to the list of Dad jokes: "What do you call a boomerang that doesn't  return?"
---
Checklist:
=> Add boomerang dad joke

config/q-expand.csv
I was q-expanding and I got an incomplete result due to missing data, so this refreshes the approximately year old source data as described in https://github.com/18F/charlie/wiki/QexEdit
---
Checklist:
=> Update q-expand data
